website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import db, User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password_hash, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        is_username_taken = User.query.filter_by(name=username).first() is not None
        if user:
            flash('Email already exists.', category='error')
        elif is_username_taken:
            flash('Username taken.', category='error')
        elif len(email) < 4 or len(email) > 49:
            flash('Email must be greater than 3 characters and less than 50', category='error')
        elif len(username) < 4 or len(username) > 19:
            flash('Username must be greater than 3 characters.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, name=username)
            new_user.set_password(password1)
            new_user.name = username
            db.session.add(new_user)
            db.session.commit()
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user

from website import redis_client, db, add_if_doesnt_exist

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
def home():
    return render_template("home.html", user=current_user)

@login_required
@views.route("/library")
def library():
    return render_template('library.html', user=current_user)


@login_required
@views.route('/search', methods=['POST'])
def search():
    query = request.form['query']

    # Perform API search here, get the results
    from website.api_service.api_utils import get_tracks
    import json
    from threading import Thread
    try:
        search_results = get_tracks(query)
        for track in search_results:
            th = Thread(target=redis_client.set, args=(track.track_id, json.dumps(track),))
            th.start()
            # redis_client.set()
    except ValueError as e:
        return render_template('error-api.html', user=current_user, message=str(e))
    # search_results = []
    # Render the search results
    return render_template('search.html', user=current_user, search_results=search_results)

@login_required
@views.route('/add_to_playlist', methods=['POST'])
def add_to_playlist():
    # Get the song from the database
    song_id = request.form['song_id']
    if not song_id:
        flash('No song provided', category='error')
        redirect(url_for('views.library'))

    add_if_doesnt_exist(song_id)

    from website.models import Song, UserSongs
    song = Song.query.get(song_id)

    user_song = UserSongs.query.filter_by(user_id=current_user.id, song_id=song.id).first()

    if user_song:
        flash('Song is already in your playlist.', 'error')
    else:
        user_song = UserSongs(user_id=current_user.id, song_id=song.id)
        db.session.add(user_song)
        db.session.commit()
        flash('Song added to playlist.', 'success')
    return redirect(url_for('views.library'))

@views.route('/mark_as_listened', methods=['POST'])
@login_required
def mark_as_listened():
    from website.models import Song, UserSongs
    song_id = request.form.get('song_id')
    song = Song.query.get(song_id)
    user_song = UserSongs.query.filter_by(user_id=current_user.id, song_id=song.id).first()

    if not user_song:
        # The song is not in the user's playlist
        flash('Song is not in your playlist.')
        return redirect(url_for('home'))

    # Mark the song as listened
    user_song.listened = not user_song.listened
    db.session.commit()
    return redirect(url_for('views.library'))

@views.route('/remove_from_playlist', methods=['POST'])
def remove_from_playlist():
    from website.models import Song, UserSongs
    song_id = request.form.get('song_id')
    song = Song.query.get(song_id)
    user_song = UserSongs.query.filter_by(user_id=current_user.id, song_id=song.id).first()

    if not user_song:
        # The song is not in the user's playlist
        flash('Song is not in your playlist.')
        return redirect(url_for('home'))

    # Remove the song from the user's playlist
    db.session.delete(user_song)
    db.session.commit()
    return redirect(url_for('views.library'))


@views.route('/library/<string:short_id>')
def user_library(short_id):
    from website.models import User, UserSongs, Song
    user = User.query.filter_by(short_id=short_id).first()
    if user:
        if current_user.is_authenticated and current_user.id == user.id:
            return redirect(url_for('views.library'))
        user_songs = db.session.query(Song).join(UserSongs, UserSongs.song_id == Song.id).filter(UserSongs.user_id == user.id).all()
        return render_template('user_playlist.html', user=current_user, inspected_user=user, songs=user_songs)
    else:
        flash("Playlist not found", "error")
        return redirect(url_for('views.playlists'))

@views.route('/playlists')
def playlists():
    from website.models import User
    users = User.query.all()
    return render_template('all_playlists.html', user=current_user, users=users)

website/templates/all_playlists.html
{% extends "base.html" %}

{% block title %}
Users
{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="my-4">Users</h1>

    <ul class="list-group">
      {% for user in users %}
      <li class="list-group-item">
        <a href="{{ url_for('views.user_library', short_id=user.short_id) }}">{{ user.name }}</a>
      </li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          {% if user and user.is_authenticated %}
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/error-api.html
{% extends "base.html" %}

{% block title %}
  Search Results
{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="my-4">Search Results</h1>

  {% if message %}
    <div class="alert alert-secondary" role="alert">
    <p>{{ message }}</p>
    </div>
  {% endif %}

    <a href="{{ url_for('views.library') }}"><button type="button" class="btn btn-link">Back to playlist</button></a>
  </div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block title %}
  Home
{% endblock %}

{% block content %}
  <div class="jumbotron">
    <h1 class="display-4">Autiotekon,</h1>
    <p class="lead">your 'listen later' library.</p>
    <hr class="my-4">
    {% if user and user.is_authenticated %}
      <p>Welcome back, {{ user.username }}!</p>
      <a class="btn btn-primary btn-lg" href="/library" role="button">Go to My Library</a>
      <a class="btn btn-primary btn-lg" href="/playlists" role="button">Browse libraries</a>
    {% else %}
      <p>Join us today and start managing your audios.</p>
      <a class="btn btn-primary btn-lg" href={{ url_for('auth.sign_up') }} role="button">Sign Up</a>
      <a class="btn btn-primary btn-lg" href="/playlists" role="button">Browse libraries</a>
    {% endif %}
  </div>
{% endblock %}

website/templates/library.html
{% extends "base.html" %}

{% block title %}
My Playlist
{% endblock %}

{% block content %}
  <div class="container">
  <h1 class="my-4">{{ user.name }}'s Playlist</h1>
  
  <form action="{{ url_for('views.search') }}" method="POST">
    <div class="input-group mb-3">
      <input type="text" class="form-control" placeholder="Search for a another song..." name="query" required>
      <div class="input-group-append">
        <button class="btn btn-primary" type="submit">Search</button>
      </div>
    </div>
  </form>
  
  <div class="card">
    <div class="card-header">
      <h2>Playlist Songs</h2>
        </div>
      <div class="card-body">
        {% for user_song in user.songs %}
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ user_song.song.name }}</h5>
            <p class="card-text">{{ user_song.song.artist }}</p>

            <div class="btn-group btn-group-lg" role="group" aria-label="...">
              <form action="{{ url_for('views.mark_as_listened') }}" method="post">
                <input type="hidden" name="song_id" value="{{ user_song.song.id }}">
                <button type="submit" class="btn {{ 'btn-primary' if user_song.listened else 'btn-success' }}">
                {{ 'Mark as Unlistened' if user_song.listened else 'Mark as Listened' }}
                </button>
              </form>

              <form action="{{ url_for('views.remove_from_playlist') }}" method="post">
                <input type="hidden" name="song_id" value="{{ user_song.song.id }}">
                <button type="submit" class="btn btn-danger">Remove from Playlist</button>
              </form>
            </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/search.html
{% extends "base.html" %}

{% block title %}
  Search Results
{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="my-4">Search Results</h1>

  {% if search_results %}
    <div class="row">
    {% for song in search_results %}
      <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">
          <div class="card-body">
            <h4 class="card-title">{{ song.track_name }}</h4>
            <h6 class="card-subtitle mb-2 text-muted">{{ song.artist_name }}</h6>
            <form action="{{ url_for('views.add_to_playlist') }}" method="POST">
              <input type="hidden" name="song_id" value="{{ song.commontrack_id }}">
              <button type="submit" class="btn btn-primary mt-2">Add to Playlist</button>
            </form>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  {% else %}
    <div class="alert alert-secondary" role="alert">
    <p>No results found.</p>
    </div>
  {% endif %}

    <a href="{{ url_for('views.library') }}"><button type="button" class="btn btn-link">Back to playlist</button></a>
  </div>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}

{% block title %}
Sign Up
{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-5">
        <h2 class="text-center">Sign Up</h2>
        <form method="POST">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email" required>
            </div>
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username" placeholder="Enter your username" required>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter your password" required>
            </div>
            <div class="form-group">
                <label for="password2">Confirm Password</label>
                <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm your password" required>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}

website/templates/user_playlist.html
{% extends "base.html" %}

{% block title %}
{{ inspected_user.name }}'s Playlist
{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="my-4">{{ inspected_user.name }}'s Playlist</h1>

    <div class="card">
      <div class="card-header">
        <h2>Playlist Songs</h2>
      </div>
      <div class="card-body">
        {% for user_song in inspected_user.songs %}
          <div class="card">
            <div class="card-body">
                <p>
                {% if user_song.listened %}
                  <span class="badge badge-success">Listened</span>
                {% else %}
                  <span class="badge badge-secondary">Not Listened</span>
                {% endif %}
              </p>

              <h5 class="card-title">{{ user_song.song.name }}</h5>
              <p class="card-text">{{ user_song.song.artist }}</p>

            </div>
          </div>
        {% else %}
          <p>No songs in this playlist yet.</p>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}